// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamMarket.Steam
{
    public partial class Item
    {
        public Item()
        {
            Inventory = new HashSet<Inventory>();
            Operation = new HashSet<Operation>();
        }

        public int IdItem { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Game { get; set; }
        public byte[] Picture { get; set; }
        public int Amount { get; set; }
        public string Description { get; set; }

        public virtual Game GameNavigation { get; set; }
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual ICollection<Operation> Operation { get; set; }
    }
}