// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SteamMarket.Steam
{
    public partial class Type
    {
        public Type()
        {
            Operation = new HashSet<Operation>();
        }

        public int IdType { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<Operation> Operation { get; set; }
    }
}